# Used for making some notes on our game dev ideas

direction: right

developement lifecycle : {

    dev1 
    dev2


    github { 
        shape: image
        icon: https://icons.terrastruct.com/dev/github.svg
    }

    dev1 -> unity : game design
    dev1 -> git : commit changes
    git -> github : push code


    dev2 <- git <- github : pull code

    

}